<?php
/**
 * Copyright (c) 2021 Zengliwei. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE AUTHORS
 * OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

use CrazyCat\Banner\Block\Widget\Carousel;

/* @var Carousel $block */
$items = $block->getItems();
$blockId = 'carousel-' . $block->getJsId();
?>
<div class="block-carousel">
    <section id="<?= $blockId ?>">
        <?php foreach ($items as $item): ?>
            <div data-type="<?= $item->getData('type') ?>">
                <?php if ($item->getData('type') == 'image') : ?>
                    <div class="image">
                        <?php if ($item->getData('url')) : ?>
                            <a <?= $item->getData('target') ? ('target="' . $item->getData('target') . '"') : '' ?>
                                href="<?= $block->getLinkUrl($item->getData('url')) ?>">
                                <img alt="<?= $block->escapeHtmlAttr($item->getData('title')) ?>"
                                     src="<?= $block->escapeHtmlAttr($block->getMediaUrl($item->getData('media'))) ?>"/>
                            </a>
                        <?php else : ?>
                            <img alt="<?= $block->escapeHtmlAttr($item->getData('title')) ?>"
                                 src="<?= $block->escapeHtmlAttr($block->getMediaUrl($item->getData('media'))) ?>"/>
                        <?php endif; ?>
                    </div>
                    <?php if ($item->getData('content')) : ?>
                        <?= $block->filterContent($item->getData('content')) ?>
                    <?php else : ?>
                        <div class="content">
                            <strong class="title"><?= $item->getData('title') ?></strong>
                        </div>
                    <?php endif; ?>
                <?php else : ?>
                    <div class="video">
                        <video muted>
                            <source src="<?= $block->getMediaUrl($item->getData('media')) ?>"/>
                        </video>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </section>
    <script>
        require(['jquery', 'carousel'], function ($) {
            const elCarousel = $('#<?= $blockId ?>');
            elCarousel.slick({
                accessibility: <?= $block->getData('accessibility') ?>,
                adaptiveHeight: <?= $block->getData('adaptive_height') ?>,
                arrows: <?= $block->getData('arrows') ?>,
                autoplay: <?= $block->getData('autoplay') ?>,
                autoplaySpeed: <?= $block->getData('autoplay_speed') ?>,
                centerMode: <?= $block->getData('center_mode') ?>,
                centerPadding: '<?= $block->getData('center_padding') ?>',
                dots: <?= $block->getData('dots') ?>,
                draggable: <?= $block->getData('draggable') ?>,
                fade: <?= $block->getData('fade') ?>,
                focusOnChange: <?= $block->getData('focus_on_change') ?>,
                focusOnSelect: <?= $block->getData('focus_on_select') ?>,
                infinite: <?= $block->getData('infinite') ?>,
                initialSlide: <?= $block->getData('initial_slide') ?>,
                lazyLoad: '<?= $block->getData('lazy_load') ?>',
                pauseOnDotsHover: <?= $block->getData('pause_on_dots_hover') ?>,
                pauseOnFocus: <?= $block->getData('pause_on_focus') ?>,
                pauseOnHover: <?= $block->getData('pause_on_hover') ?>,
                respondTo: 'min',
                rows: <?= $block->getData('rows') ?>,
                rtl: <?= $block->getData('rtl') ?>,
                slidesPerRow: <?= $block->getData('slides_per_row') ?>,
                slidesToScroll: <?= $block->getData('slides_to_scroll') ?>,
                slidesToShow: <?= $block->getData('slides_to_show') ?>,
                speed: <?= $block->getData('speed') ?>,
                swipe: <?= $block->getData('swipe') ?>,
                swipeToSlide: <?= $block->getData('swipe_to_slide') ?>,
                touchMove: <?= $block->getData('touch_move') ?>,
                touchThreshold: <?= $block->getData('touch_threshold') ?>,
                variableWidth: <?= $block->getData('variable_width') ?>,
                vertical: <?= $block->getData('vertical') ?>,
                verticalSwiping: <?= $block->getData('vertical_swiping') ?>,
                waitForAnimate: <?= $block->getData('wait_for_animate') ?>,
                responsive: [{
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: <?= min($block->getData('slides_to_show'), 5) ?>
                    }
                }, {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: <?= min($block->getData('slides_to_show'), 2) ?>
                    }
                }, {
                    breakpoint: 375,
                    settings: {
                        slidesToShow: 1
                    }
                }]
            }).on('afterChange', function (evt, slick, currentSlide, nextSlide) {
                const elCurrentItem = $(slick.$slides[currentSlide]);
                if (elCurrentItem.data('type') == 'video') {
                    elCarousel.slick('slickPause');
                    elCurrentItem.find('video')
                        .one('ended', function () {
                            elCarousel.slick('slickPlay');
                        })
                        .get(0).play();
                }
            });
        });
    </script>
</div>
