<?php

use Common\Banner\Block\Widget\Carousel;

/* @var Carousel $block */
$items = $block->getItems();
?>
<div class="block-carousel">
    <section class="vertical slider" data-role="carousel">
        <?php foreach ($items as $item): ?>
            <div>
                <div class="media">
                    <?php if ($item->getData('type') == 'image') : ?>
                        <?php if ($item->getData('url')) : ?>
                            <a href="<?= $block->getLinkUrl($item->getData('url')) ?>">
                                <img src="<?= $block->getMediaUrl($item->getData('media')) ?>"/>
                            </a>
                        <?php else : ?>
                            <img src="<?= $block->getMediaUrl($item->getData('media')) ?>"/>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <?php if ($item->getData('content')) : ?>
                    <?= $item->getData('content') ?>
                <?php else : ?>
                    <div class="content">
                        <strong class="title"><?= $item->getData('title') ?></strong>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </section>
    <script>
        require(['jquery', 'carousel'], function ($) {
            $('[data-role="carousel"]').slick({
                autoplay: true,
                autoplaySpeed: 3000,
                arrows: true,
                dots: true,
                infinite: true
            });
        });
    </script>
</div>
